### ISSUE TITLE
HTTP 403: forbidden when publishing to oss.jfrog.org with artifactory-maven-plugin

### ISSUE THREAD

**Issue by michaz** [JFrogDev/build-info#63]
Hi,

I get the following when deploying **a snapshot** to **oss.jfrog.org** with the artifactory-maven-plugin:
```
Caused by: java.io.IOException: Failed to deploy file: HTTP response code: 403. HTTP response message: Forbidden
        at org.jfrog.build.extractor.clientConfiguration.client.ArtifactoryBuildInfoClient.throwHttpIOException(ArtifactoryBuildInfoClie
nt.java:743)
        at org.jfrog.build.extractor.clientConfiguration.client.ArtifactoryBuildInfoClient.uploadFile(ArtifactoryBuildInfoClient.java:62
3)
        at org.jfrog.build.extractor.clientConfiguration.client.ArtifactoryBuildInfoClient.deployArtifact(ArtifactoryBuildInfoClient.jav
a:329)
        at org.jfrog.build.extractor.maven.BuildDeploymentHelper.deployArtifacts(BuildDeploymentHelper.java:275)
```

Using this configuration:

```			
<plugin>
				<groupId>org.jfrog.buildinfo</groupId>
				<artifactId>artifactory-maven-plugin</artifactId>
				<version>2.4.0</version>
				<inherited>false</inherited>
				<executions>
					<execution>
						<id>build-info</id>
						<goals>
							<goal>publish</goal>
						</goals>
						<configuration>
							<publisher>
								<contextUrl>https://oss.jfrog.org</contextUrl>
								<username>michaz</username>
								<password>...</password>
								<repoKey>libs-release-local</repoKey>
								<snapshotRepoKey>libs-snapshot-local</snapshotRepoKey>
							</publisher>
						</configuration>
					</execution>
				</executions>
</plugin>

```			

It works, however, when I simply mvn deploy without the plugin, using

```
	<distributionManagement>
		<snapshotRepository>
			<id>oss-jfrog-artifactory</id>
			<name>artifactory-snapshots</name>
			<url>http://oss.jfrog.org/oss-snapshot-local</url>
		</snapshotRepository>
	</distributionManagement>
```

Any idea what I'm missing?
Is the plugin trying to overwrite or delete something on **oss.jfrog.org** for which I don't have permission?

**Comment by eyalbe4** [comment]
It looks like in the "mvn deploy" example you're deploying to the oss-snapshot-local repository, while in the Artifactory maven plugin example you're deploying to the libs-release-local 
repository.
There doesn't seem to be a repository named libs-release-local in oss.JFrog.org.
There are however:
https://oss.jfrog.org/artifactory/oss-release-local/
And
https://oss.jfrog.org/artifactory/oss-snapshot-local/

Using the Artifactory Maven Plugin instead of mvn deploy is recommended because of the following reasons:
1. It deploys all of your build artifacts and the end of the build, and thas assuring that there is no partial deployment.
2. It deploys the build Info in addition to all of your bills artifact.

**Comment by michaz** [comment]
Phew. Thanks Eyal, I kept missing this even though I looked at it for perhaps 50 times.
